version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    networks:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"

  backend:
    build:
      context: ./lib_catalog
    container_name: "backend"
    networks:
      - app
    ports:
      - "8000:8000"
  
  database:
    image: postgres:14-alpine
    container_name: "database"
    environment:
      - POSTGRES_USER=django
    env_file:
      - .env
    networks:
      - app

networks:
  app: